local_backend: false
backend:
  repo: khanetor/kha-linh-wedding
  squash_merges: true
  name: github
publish_mode: editorial_workflow
i18n:
  structure: multiple_folders
  locales:
    - en
    - vi
  default_locale: en
media_library:
  name: cloudinary
  config:
    cloud_name: khalinh-wedding
    api_key: "562894652481875"
media_folder: src/public
collections:
  - name: pages
    label: Pages
    i18n:
      structure: single_file
      locales:
        - en
        - vi
    files:
      - name: home
        label: Home
        file: index.md
        i18n: true
        fields:
          - name: layout
            default: home
            widget: string
          - name: hero
            label: Hero
            fields:
              - name: name
                label: Name
                i18n: true
                widget: string
              - name: text
                label: Text
                i18n: true
                widget: string
              - name: tagline
                label: Tagline
                i18n: true
                widget: string
              - name: actions
                label: Tagline
                fields:
                  - name: theme
                    options:
                      - brand
                      - alt
                    widget: select
                  - name: text
                    i18n: true
                    widget: string
                  - name: link
                    i18n: true
                    widget: string
                widget: list
            widget: object
          - name: features
            label: Features
            fields:
              - name: title
                i18n: true
                widget: string
              - name: details
                i18n: true
                widget: string
            widget: list
          - name: body
            i18n: true
            widget: markdown
      - name: story
        label: Our Story
        file: story.md
        i18n: true
        fields:
          - name: title
            i18n: true
            widget: string
          - name: body
            i18n: true
            widget: markdown
      - name: details
        label: Wedding Details
        file: details.md
        i18n: true
        fields:
          - name: title
            i18n: true
            widget: string
          - name: body
            i18n: true
            widget: markdown
      - name: rsvp
        label: RSVP
        file: rsvp.md
        i18n: true
        fields:
          - name: title
            i18n: true
            widget: string
          - name: body
            i18n: true
            widget: markdown
      - name: gallery
        label: Gallery
        file: gallery.md
        i18n: true
        fields:
          - name: title
            i18n: true
            widget: string
          - name: images
            field:
              name: image
              widget: image
            widget: list
