local_backend: false
backend:
  repo: khanetor/kha-linh-wedding
  squash_merges: true
  name: github
publish_mode: editorial_workflow
i18n:
  structure: multiple_folders
  locales:
    - en
    - vi
  default_locale: en
media_library:
  name: cloudinary
  config:
    cloud_name: khalinh-wedding
    api_key: "562894652481875"
media_folder: src/public
collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home
        file: index.md
        fields:
          - name: layout
            default: home
            widget: string
          - name: body
            widget: markdown
      - name: story
        label: Our Story
        file: story.md
        fields:
          - name: title
            widget: string
          - name: body
            widget: markdown
      - name: details
        label: Wedding Details
        file: details.md
        fields:
          - name: title
            widget: string
          - name: body
            widget: markdown
      - name: rsvp
        label: RSVP
        file: rsvp.md
        fields:
          - name: title
            widget: string
          - name: body
            widget: markdown
      - name: gallery
        label: Gallery
        file: gallery.md
        fields:
          - name: title
            widget: string
          - name: images
            field:
              name: image
              widget: image
            widget: list
